package com.zyw.manage.domain.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`manage_order`")
public class OrderEntity {
    @Id
    private Long id;

    private Long partnerId;

    private Long productId;

    private Long count;

    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.is_deleted
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.creator
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.gmt_created
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.modifier
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.gmt_modified
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.id
     *
     * @return the value of manage_order.id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.id
     *
     * @param id the value for manage_order.id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.partner_id
     *
     * @return the value of manage_order.partner_id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Long getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.partner_id
     *
     * @param partnerId the value for manage_order.partner_id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.product_id
     *
     * @return the value of manage_order.product_id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.product_id
     *
     * @param productId the value for manage_order.product_id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.count
     *
     * @return the value of manage_order.count
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.count
     *
     * @param count the value for manage_order.count
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.order_time
     *
     * @return the value of manage_order.order_time
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.order_time
     *
     * @param orderTime the value for manage_order.order_time
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.is_deleted
     *
     * @return the value of manage_order.is_deleted
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.is_deleted
     *
     * @param isDeleted the value for manage_order.is_deleted
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.creator
     *
     * @return the value of manage_order.creator
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.creator
     *
     * @param creator the value for manage_order.creator
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.gmt_created
     *
     * @return the value of manage_order.gmt_created
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.gmt_created
     *
     * @param gmtCreated the value for manage_order.gmt_created
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.modifier
     *
     * @return the value of manage_order.modifier
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.modifier
     *
     * @param modifier the value for manage_order.modifier
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_order.gmt_modified
     *
     * @return the value of manage_order.gmt_modified
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_order.gmt_modified
     *
     * @param gmtModified the value for manage_order.gmt_modified
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}