package com.zyw.manage.domain.entity;

import lombok.Data;

import java.util.Date;
import javax.persistence.*;

@Data
@Table(name = "`manage_order`")
public class OrderEntity {
    @Id
    private Long id;

    private Long partnerId;

    private Long productId;

    private Long count;

    private Date orderTime;
    @Transient
    private String orderTimeStr;

    @Transient
    private String productName;
    @Transient
    private String partnerName;

    public void setOrderTime(Date orderTime){
        this.orderTime = orderTime;
//        this.orderTimeStr =
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.is_deleted
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String isDeleted = "N";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.creator
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String creator = "SYSTEM";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.gmt_created
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.modifier
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_order.gmt_modified
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private Date gmtModified;

}