package com.zyw.manage.domain.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`manage_partner`")
public class PartnerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_partner.id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    @Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_partner.partner_name
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String partnerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_partner.is_deleted
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_partner.creator
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_partner.gmt_created
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_partner.modifier
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_partner.gmt_modified
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_partner.id
     *
     * @return the value of manage_partner.id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_partner.id
     *
     * @param id the value for manage_partner.id
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_partner.partner_name
     *
     * @return the value of manage_partner.partner_name
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_partner.partner_name
     *
     * @param partnerName the value for manage_partner.partner_name
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_partner.is_deleted
     *
     * @return the value of manage_partner.is_deleted
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_partner.is_deleted
     *
     * @param isDeleted the value for manage_partner.is_deleted
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_partner.creator
     *
     * @return the value of manage_partner.creator
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_partner.creator
     *
     * @param creator the value for manage_partner.creator
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_partner.gmt_created
     *
     * @return the value of manage_partner.gmt_created
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_partner.gmt_created
     *
     * @param gmtCreated the value for manage_partner.gmt_created
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_partner.modifier
     *
     * @return the value of manage_partner.modifier
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_partner.modifier
     *
     * @param modifier the value for manage_partner.modifier
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_partner.gmt_modified
     *
     * @return the value of manage_partner.gmt_modified
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_partner.gmt_modified
     *
     * @param gmtModified the value for manage_partner.gmt_modified
     *
     * @mbg.generated Sun Nov 10 20:58:01 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}